# Generated by Django 5.0.1 on 2024-01-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='finance',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='finance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.FileField(default='default_profile.jpg', upload_to='profile_pic/'),
        ),
    ]
