# Generated by Django 5.0.1 on 2024-01-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackify', '0002_remove_userprofile_username_finance_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default_profile.jpg', upload_to='profile_pic/'),
        ),
    ]
